### ISSUE TITLE
Incorrect mixing of javadoc defined at reporting

### ISSUE THREAD

**Issue by rrialq** [odavid/maven-plugins#5] opened 2015-08-04 17:14 UTC
Hello. This is a very useful plugin, maybe the most useful plugin I've seen till now.
I've just discovered what I think is a bug.
If you configure the javadoc plugin at reporting section (and surefire too) as defined in module **mixin-reports**, the demo fails after:

``` bash
mvn site
```

With the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site 
(default-site) on project mixin-demo: failed to get report for
org.apache.maven.plugins:maven-project-info-reports-plugin:
Plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.10.3
or one of its dependencies could not be resolved
```

The problem is a bad mixing at reporting. After

```
mvn -B help:effective-pom > effective-pom.xml
```

I found that the **maven-project-info-reports-plugin** is configured with the reportSets configuration of the plugin **javadoc**.

After a little testing I've just discovered a possible tip about the error:
**com.github.odavid.maven.plugins.MixinsProjectLoader.mergeMixins** is the method that fails, and when I comment the following line inside this method the report is generated OK:

``` Java
mixinModelMerger.applyPluginManagementOnPlugins(mavenProject.getModel());
```

More info: following the code, the problem seems to be in **com.github.odavid.maven.plugins.MixenModelMerger.mergePluginContainers(...)** method; with the commented line it works, but I don't known the collateral effects:

``` Java
//super.mergeConfigurationContainer( targetPlugin, sourcePlugin, false, context);
super.mergePlugin_GroupId( targetPlugin, sourcePlugin, false, context);
super.mergePlugin_ArtifactId( targetPlugin, sourcePlugin, false, context);
super.mergePlugin_Version( targetPlugin, sourcePlugin, false, context);
super.mergePlugin_Extensions( targetPlugin, sourcePlugin, false, context );
super.mergePlugin_Dependencies( targetPlugin, sourcePlugin, false, context);
```

I hope this should be useful.

You can find the [demo project here](http://s000.tinyupload.com/index.php?del_id=79597525679189419158) to replicate the issue.

**Comment by odavid** [comment] 2015-08-04 21:17
Hi, thanks for the feedback and the demo project!
After testing the demo, I found out there is a problem with merging the reporting section.
The problem is actually in maven core and it is related to the fact that the reporting section is being converted into site-plugin:reportPlugins. The issue is that the configuration of the site plugin is not merged correctly, since it is a plain xml merge and not logical merge like in any other section in the pom.
See https://issues.apache.org/jira/browse/MSITE-484 for more details.
I need to figure out how to overcome this issue, but it will take some time.
Regards,
Ohad

**Comment by odavid** [comment] 2015-08-04 22:15
Hi again...
I solved this issue by removing all reportPlugins from the configuration of site-plugin (only if the pom contained reporting section) and after the mixin merge, the conversion to site-plugin reportPlugins is done again. By that I am simulating the same logic maven uses today with the parent pom merges.

Hope this helps,
Ohad

**Comment by rrialq** [comment] 2015-08-05 17:28
Thank you. I am testing the master branch and it works fine!

**Closed as completed** 2015-08-09 20:36 UTC
